<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Customer\Block\Account\AuthorizationLink $block
 * @var \Magento\Framework\Escaper $escaper
 */
$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
if ($escaper->escapeHtml($block->getLabel()) == 'Se connecter'){
?>
	<div>
	<li class="link authorization-link" data-label="<?= $escaper->escapeHtml(__('or')) ?>">
		<a <?= /* @noEscape */ $block->getLinkAttributes() ?>
			<?= /* @noEscape */ $dataPostParam ?>><?= $escaper->escapeHtml($block->getLabel()) ?></a>
	</li>
<?php
}else{
	?>
	<div class="connected">
	<li class="link authorization-link deco" data-label="<?= $escaper->escapeHtml(__('or')) ?>">
		<a <?= /* @noEscape */ $block->getLinkAttributes() ?>
			<?= /* @noEscape */ $dataPostParam ?>><?= $escaper->escapeHtml($block->getLabel()) ?></a>
	</li>
	<?php
}