<script>
    require(['jquery', 'owl.carousel', 'domReady!'], function ($) {
        'use strict';
        $('.owl-carousel').owlCarousel({
            loop:false,
            margin:10,
            nav:true,
            autoplay:true,
            autoplayTimeout:5000,
            responsive:{
                0:{
                    items:1
                },
                600:{
                    items:3
                },
                1000:{
                    items:5
                }
            }
        })
    });
</script>
<?php
$uri = explode('/', $_SERVER['REQUEST_URI']);
?>

<h2><strong>Les produits du vendeur</strong></h2>

<div class="owl-carousel owl-theme">
    <?php

    $productCollection = $block->getProductCollection($uri[5]);
    $productCollection->getSelect()->limit(25);
    /** @var \Magento\Catalog\Model\Product $product */
    foreach ($productCollection as $product) : ?>
        <div class="seller product">
            <?php
            $product_name = $block->escapeHtml($product->getName());
            $truncated = (strlen($product_name) > 40) ? substr($product_name, 0, 40) . '...' : $product_name ;
            $image_url = $block->imageHelperObj()->init($product, 'product_page_image_small')
                ->setImageFile($product->getFile())
                ->resize($this->getProductimagewidth(), $this->getProductimageheight())
                ->getUrl();
            ?>
            <a href="<?php  echo $product->getProductUrl() ?>" class="product_img_seller" >
                <img class="product seller" src="<?php echo  $image_url;?>" alt="<?php echo $this->escapeHtml($product->getName()) ?>" />
            </a>
            <a href="<?php  echo $product->getProductUrl() ?>" class="product_name_seller" >
                <?= $truncated ?>
            </a>

            <p class="slider_product_price"><?= $product->getFinalPrice() ?> €</p>
            <?php if ($product->isSaleable()) :?>
                <a href="<?php  echo $product->getProductUrl() ?>">
                    <button class="seeproduct">
                        Voir le produit
                    </button>
                </a>
            <?php else :?>
                <?php if ($product->getIsSalable()) :?>
                    <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                <?php else :?>
                    <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
</div>
