<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
      integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
<!--div class="wishlist_button">
    <a class="wishlit_link" href="https://europazon.fr/wishlist/">

    </a>
</div-->
<div class="header-wish">
    <div class="customer-welcome wishlist_button">
        <button
            data-mage-init='{"dropdown":{}}'
            data-toggle="dropdown"
            class="action"
            data-action="customer-menu-toggle">
            <i class="fas fa-heart"></i>
            <div class="header-wish-txt">
                <p class="bold">Mes favoris</p>
                <p class="little">Voir ma liste</p>
            </div>
        </button>
        <ul data-target="dropdown" class="dropdown-options">
            <li>
                <span class="item"><a href="/wishlist">Liste de souhait</a></span>
            </li>
            <li>
                <span class="item"><a href="/alerte-de-prix">Créer une alerte de prix</a></span>
            </li>
            <li>
                <span class="item"><a href="/catalog/product_compare/">Comparateur de prix</a></span>
            </li>
        </ul>
    </div>
</div>
