<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
      integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
<!--div class="tips_button">
    <a class="tips_link">
        <i class="fas fa-question"></i>
        <div class="header-aide-txt">
            <p class="bold">Aide FAQ</p>
        </div>
    </a>
    <ul data-target="dropdown" class="dropdown-options tips" style="display:none;">
        <li>
            <span class="item"><a href="/faq">FAQ</a></span>
        </li>
        <li>
            <span class="item"><a href="/contact">Nous Contacter</a></span>
        </li>
    </ul>
</div-->

<div class="tips_button">
    <div class="customer-welcome tips_button">
        <button
            data-mage-init='{"dropdown":{}}'
            data-toggle="dropdown"
            class="action"
            data-action="customer-menu-toggle">
            <i class="fas fa-question"></i>
            <div class="header-aide-txt">
                <p class="bold">Aide FAQ</p>
            </div>
        </button>
        <ul data-target="dropdown" class="dropdown-options">
            <li>
                <span class="item"><a href="/faq">FAQ</a></span>
            </li>
            <li>
                <span class="item"><a href="/contact">Nous Contacter</a></span>
            </li>
        </ul>
    </div>
</div>
